; autogenerated by generate_llvm_assembler.pl. 

@printf_st = private unnamed_addr constant [37 x i8] c"this prints if poison-free: '0x%x' \0A\00"

; external declaration of the printf(~) function 
declare i32 @printf(i8* nocapture readonly, ...)


define i10 @main() { ; 
  ; %convert [? x i8]* to i8* 
  %printf_st_i8 = getelementptr [37 x i8]* @printf_st, i64 0, i64 0

  %1= add i10 1019, 0 
  %2= add i10 528, 0 
  %3= srem i10 %1, %2
  %4= srem i10 %3, %1
  %5= and i10 %1, %4
  %6= sub nuw i10 %5, 93
  %7= lshr i10 %6, 8
  %8= ashr exact i10 %7, 9
  %9= udiv i10 %8, 841
  %10= add i10 444, %9
  %11= sub i10 %10, %8
  %12= mul i10 %11, 236

  call i32 (i8*, ...)* @printf(i8* %printf_st_i8, i10 %12)

  ; clean up and return 
  ret i10 0 
} 

; end of program 

