; autogenerated by generate_llvm_assembler.pl. 

@printf_st = private unnamed_addr constant [37 x i8] c"this prints if poison-free: '0x%x' \0A\00"

; external declaration of the printf(~) function 
declare i32 @printf(i8* nocapture readonly, ...)


define i11 @main() { ; 
  ; %convert [? x i8]* to i8* 
  %printf_st_i8 = getelementptr [37 x i8]* @printf_st, i64 0, i64 0

  %1= add i11 213, 0 
  %2= add i11 709, 0 
  %3= mul nsw nuw i11 %1, %2
  %4= sub nsw i11 371, %3
  %5= urem i11 %4, %1
  %6= mul nsw nuw i11 %4, %5
  %7= or i11 %6, 657
  %8= add nuw i11 %7, 140
  %9= add i11 %8, 1330
  %10= udiv exact i11 %9, 1506
  %11= and i11 %7, %10
  %12= ashr exact i11 %11, 8

  call i32 (i8*, ...)* @printf(i8* %printf_st_i8, i11 %12)

  ; clean up and return 
  ret i11 0 
} 

; end of program 

