; autogenerated by generate_llvm_assembler.pl. 

@printf_st = private unnamed_addr constant [37 x i8] c"this prints if poison-free: '0x%x' \0A\00"

; external declaration of the printf(~) function 
declare i32 @printf(i8* nocapture readonly, ...)


define i19 @main() { ; 
  ; %convert [? x i8]* to i8* 
  %printf_st_i8 = getelementptr [37 x i8]* @printf_st, i64 0, i64 0

  %1= add i19 472132, 0 
  %2= add i19 119074, 0 
  %3= add nsw i19 %2, 189556
  %4= sdiv i19 %3, %1
  %5= srem i19 %3, %4
  %6= shl nsw i19 %5, 18
  %7= mul nsw nuw i19 %6, 103787
  %8= shl i19 %7, 13
  %9= lshr i19 %8, 0
  %10= udiv i19 %9, 407550
  %11= udiv exact i19 %10, 181157
  %12= or i19 %11, %4

  call i32 (i8*, ...)* @printf(i8* %printf_st_i8, i19 %12)

  ; clean up and return 
  ret i19 0 
} 

; end of program 

