; autogenerated by generate_llvm_assembler.pl. 

@printf_st = private unnamed_addr constant [37 x i8] c"this prints if poison-free: '0x%x' \0A\00"

; external declaration of the printf(~) function 
declare i32 @printf(i8* nocapture readonly, ...)

@addr_hjfp = global i13 4845
@addr_zqyh = global i13 560

define i13 @main() { ; 
  ; %convert [? x i8]* to i8* 
  %printf_st_i8 = getelementptr [37 x i8]* @printf_st, i64 0, i64 0

  %1= add i13 3610, 0 
  %2= add i13 973, 0 
  %3= or i13 %1, %2
  store  i13 %3, i13* @addr_hjfp
  %4= load i13* @addr_hjfp 
  %5= or i13 %4, 651
  store  i13 %5, i13* @addr_zqyh
  %6= load i13* @addr_zqyh 
  %7= sdiv i13 %6, 8008
  %8= lshr i13 %7, 6
  %9= sdiv i13 %8, %2
  %10= ashr exact i13 %9, 8
  %11= or i13 %10, 1758
  %12= and i13 %11, 3381

  call i32 (i8*, ...)* @printf(i8* %printf_st_i8, i13 %12)

  ; clean up and return 
  ret i13 0 
} 

; end of program 

